// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $FixedShippingSimulation from "./islands/FixedShippingSimulation.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $MeasurementChart from "./islands/MeasurementChart.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OurStores from "./islands/OurStores.jsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductSimilars from "./islands/ProductSimilars.tsx";
import * as $Resellers from "./islands/Resellers.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SellersSelector from "./islands/SellersSelector.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import * as $utils_Map from "./islands/utils/Map.js";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/FixedShippingSimulation.tsx": $FixedShippingSimulation,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/MeasurementChart.tsx": $MeasurementChart,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OurStores.jsx": $OurStores,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductSimilars.tsx": $ProductSimilars,
    "./islands/Resellers.tsx": $Resellers,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SellersSelector.tsx": $SellersSelector,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/WishlistButton.tsx": $WishlistButton,
    "./islands/utils/Map.js": $utils_Map,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
